### ISSUE TITLE
Set an error page for wrong input and input not available in database.

### ISSUE THREAD

**Issue by MayV** [MayV/DelhiTravelNavigator#14]

**Comment by pegasus-lynx** [comment]
I want to work on this issue.

**Comment by MayV** [comment]
The issue has been resolved for metro app but not for bus app.
@pegasus-lynx you can work on bus app.

**Comment by pegasus-lynx** [comment]
I am on it

**Comment by MayV** [comment]
Okk 👍

**Comment by MayV** [comment]
This issue has been resolved. Thanks @pegasus-lynx  and @shivamgupta077 for working on it.
