### ISSUE TITLE
Style and improve metro app templates.

### ISSUE THREAD

**Issue by MayV** [MayV/DelhiTravelNavigator#2]
Do not edit forms. Just style it.

**Comment by pegasus-lynx** [comment]
Do you have some particular styles in mind ?

**Comment by pegasus-lynx** [comment]
I would like to work on this issue. Do you have any particular idea or style that you would like to be implemented here

**Comment by MayV** [comment]
No particular style. You can design it in any way.

**Comment by MayV** [comment]
Currently no need.
